name: "Build & Deploy Docker"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TAG: ghcr.io/michiganlabs/hack-the-lab-dashboard:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.TAG }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-run-app.yml
    secrets: inherit