name: "Deploy Docker"

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  run_container:
    runs-on: 
      labels: [ "self-hosted", "Linux" ]

    env:
      TAG: "ghcr.io/michiganlabs/hack-the-lab-dashboard:latest"
    
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Pull docker image
        run: docker pull $TAG

      - name: stop any existing containers
        run: docker compose -f docker-compose.prod.yml down --remove-orphans

      - name: execute container
        run: docker compose -f docker-compose.prod.yml up -d